import HeaderNav from "@/components/header-nav";
import type { Metadata } from "next";
import "./globals.css";

import { Poppins } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <>
          <HeaderNav />
          {children}
        </>
      </body>
    </html>
  );
}
